[package]
name = "rust-stuff"
version = "0.1.0"
edition = "2021"
authors = ["rafe: https://github.com/EsinShadrach"]
description = "A collection of rust stuff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
